phrase = "many moons"
phrase_expanded = phrase + " and many stars"
phrase_larger = phrase_expanded + " litter"
phrase_complete = "M" + phrase_larger[1:] + "the night sky."
excited_phrase_complete = phrase_complete[:-1] + "!"
